// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPYxmY_CCYbfZ-Jlx9OnU7GEq2M-Lk1J4',
    appId: '1:18742118886:web:c9c6668b8adbb3a8eb6e27',
    messagingSenderId: '18742118886',
    projectId: 'cookmate-47b75',
    authDomain: 'cookmate-47b75.firebaseapp.com',
    storageBucket: 'cookmate-47b75.firebasestorage.app',
    measurementId: 'G-3BEYW7K0C5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmP2RayyT4D74jh-Tx5B_2Tvoxc4RLoCA',
    appId: '1:18742118886:android:19215e33de019e0deb6e27',
    messagingSenderId: '18742118886',
    projectId: 'cookmate-47b75',
    storageBucket: 'cookmate-47b75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxh7OLOBFcIcMJOh83IBXsI5fgppvRgZo',
    appId: '1:18742118886:ios:99637aea6ff4d86beb6e27',
    messagingSenderId: '18742118886',
    projectId: 'cookmate-47b75',
    storageBucket: 'cookmate-47b75.firebasestorage.app',
    iosBundleId: 'com.example.cookmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxh7OLOBFcIcMJOh83IBXsI5fgppvRgZo',
    appId: '1:18742118886:ios:99637aea6ff4d86beb6e27',
    messagingSenderId: '18742118886',
    projectId: 'cookmate-47b75',
    storageBucket: 'cookmate-47b75.firebasestorage.app',
    iosBundleId: 'com.example.cookmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPYxmY_CCYbfZ-Jlx9OnU7GEq2M-Lk1J4',
    appId: '1:18742118886:web:9b0e600c8619278aeb6e27',
    messagingSenderId: '18742118886',
    projectId: 'cookmate-47b75',
    authDomain: 'cookmate-47b75.firebaseapp.com',
    storageBucket: 'cookmate-47b75.firebasestorage.app',
    measurementId: 'G-HT0M7GK2XD',
  );
}
